use_frameworks!

platform :ios, '13.0'

target 'CompositionalGridView_Example' do
  pod 'CompositionalGridView', :path => '../'

  target 'CompositionalGridView_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
