# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro']

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild clean build -scheme CompositionalGridView -destination "name=iPhone 14 Pro,OS=16.2"
    - name: Run tests
      run: xcodebuild clean test -project CompositionalGridView.xcodeproj -scheme CompositionalGridView-Example -destination "name=iPhone 14 Pro,OS=16.2"

